######################################################################
#
# File name : tb_clk_wave.do
# Created on: Fri Sep 25 15:15:27 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
