######################################################################
#
# File name : tb_clk_simulate.do
# Created on: Fri Sep 25 19:53:18 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L blk_mem_gen_v8_4_2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_clk xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_clk_wave.do}

view wave
view structure
view signals

log -r /*

do {tb_clk.udo}

run 10000ns
