######################################################################
#
# File name : tb_master_compile.do
# Created on: Fri Sep 25 15:13:29 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.6d\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.6d\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../karatsuba_mult.srcs/sources_1/new" "+incdir+../../../../karatsuba_mult.srcs/sources_1/ip/ip_clk_pll_x2" \
"../../../../karatsuba_mult.srcs/sources_1/ip/ip_clk_pll_x2/ip_clk_pll_x2_sim_netlist.v" \
"../../../../karatsuba_mult.srcs/sources_1/new/master_clk.v" \
"../../../../karatsuba_mult.srcs/sim_1/new/tb_master.v" \


# compile glbl module
C:\\modeltech64_10.6d\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

