######################################################################
#
# File name : tb_master_simulate.do
# Created on: Fri Sep 25 15:13:35 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_master xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_master_wave.do}

view wave
view structure
view signals

log -r /*

do {tb_master.udo}

run 3600ns
