######################################################################
#
# File name : tb_singROM_256x128_control_wave.do
# Created on: Thu Sep 24 22:18:40 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
