######################################################################
#
# File name : tb_singROM_256x128_control_simulate.do
# Created on: Fri Sep 25 09:47:55 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L blk_mem_gen_v8_4_2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.tb_singROM_256x128_control xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_singROM_256x128_control_wave.do}

view wave
view structure
view signals

log -r /*

do {tb_singROM_256x128_control.udo}

run 3600ns
