# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/1desktop/kara_MMCM_FIFO_ver7.4/karatsuba_mult.srcs/sources_1/ip/ip_fifo_256x64/ip_fifo_256x64.xci
# IP: The module: 'ip_fifo_256x64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/1desktop/kara_MMCM_FIFO_ver7.4/karatsuba_mult.srcs/sources_1/ip/ip_fifo_256x64/ip_fifo_256x64.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_fifo_256x64'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/1desktop/kara_MMCM_FIFO_ver7.4/karatsuba_mult.srcs/sources_1/ip/ip_fifo_256x64/ip_fifo_256x64_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_fifo_256x64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/1desktop/kara_MMCM_FIFO_ver7.4/karatsuba_mult.srcs/sources_1/ip/ip_fifo_256x64/ip_fifo_256x64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_fifo_256x64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/1desktop/kara_MMCM_FIFO_ver7.4/karatsuba_mult.srcs/sources_1/ip/ip_fifo_256x64/ip_fifo_256x64.xci
# IP: The module: 'ip_fifo_256x64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/1desktop/kara_MMCM_FIFO_ver7.4/karatsuba_mult.srcs/sources_1/ip/ip_fifo_256x64/ip_fifo_256x64.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_fifo_256x64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/1desktop/kara_MMCM_FIFO_ver7.4/karatsuba_mult.srcs/sources_1/ip/ip_fifo_256x64/ip_fifo_256x64_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_fifo_256x64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/1desktop/kara_MMCM_FIFO_ver7.4/karatsuba_mult.srcs/sources_1/ip/ip_fifo_256x64/ip_fifo_256x64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_fifo_256x64'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
