# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/1desktop/kara_MMCM_FIFO_ver7.4/karatsuba_mult.srcs/sources_1/ip/ip_clk_pll_x2/ip_clk_pll_x2.xci
# IP: The module: 'ip_clk_pll_x2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/1desktop/kara_MMCM_FIFO_ver7.4/karatsuba_mult.srcs/sources_1/ip/ip_clk_pll_x2/ip_clk_pll_x2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_clk_pll_x2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/1desktop/kara_MMCM_FIFO_ver7.4/karatsuba_mult.srcs/sources_1/ip/ip_clk_pll_x2/ip_clk_pll_x2.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_clk_pll_x2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/1desktop/kara_MMCM_FIFO_ver7.4/karatsuba_mult.srcs/sources_1/ip/ip_clk_pll_x2/ip_clk_pll_x2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_clk_pll_x2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/1desktop/kara_MMCM_FIFO_ver7.4/karatsuba_mult.srcs/sources_1/ip/ip_clk_pll_x2/ip_clk_pll_x2.xci
# IP: The module: 'ip_clk_pll_x2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/1desktop/kara_MMCM_FIFO_ver7.4/karatsuba_mult.srcs/sources_1/ip/ip_clk_pll_x2/ip_clk_pll_x2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_clk_pll_x2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/1desktop/kara_MMCM_FIFO_ver7.4/karatsuba_mult.srcs/sources_1/ip/ip_clk_pll_x2/ip_clk_pll_x2.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_clk_pll_x2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/1desktop/kara_MMCM_FIFO_ver7.4/karatsuba_mult.srcs/sources_1/ip/ip_clk_pll_x2/ip_clk_pll_x2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ip_clk_pll_x2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
